exclude_paths:
  # Exclude known non-UTF8 file causing decoding errors in Codacy CLI
  - f821_errors.json
  # Exclude instruction/markdown directories that are not relevant for code analysis and may include non-UTF-8 bytes
  - .github/instructions/**
  - docs/**
