# Ruff設定ファイル

# 行の長さ
line-length = 120

# Lint 設定（旧 top-level extend-* は lint.* 配下へ移行）
[lint]
extend-ignore = [
    "E402", # module level import not at top of file
    "C901", # function is too complex
]

# ファイル別の無視ルール
[lint.extend-per-file-ignores]
"**/apps/*.py" = ["E402", "F401", "F403"]
