[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
src_paths = [
  "common",
  "core",
  "strategies",
  "config",
  "scripts",
  "tools",
]
force_sort_within_sections = true

[tool.ruff]
target-version = "py310"
line-length = 100
extend-exclude = ["data_cache", "results_csv", "logs"]
lint.select = ["E", "F", "B", "UP", "N"]
lint.ignore = [
  # pytestの未使用引数や命名など、既存テスト互換のために一部緩める
  "N802",
  "N803",
  "N806",
]

[tool.pytest.ini_options]
addopts = "--cov=./ --cov-report=term-missing"
