name: CI (retired)

# このワークフローは ci-unified.yml に統合されたため自動トリガーを停止しました。
# 必要に応じて他のワークフローから呼び出して再利用可能にします。
on:
  workflow_call:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint & Test (Ubuntu)
    runs-on: ubuntu-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONUNBUFFERED: 1
      COMPACT_TODAY_LOGS: "1"
      ENABLE_PROGRESS_EVENTS: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Pin formatting tool versions
        run: |
          # Ensure CI uses the same formatter versions as pre-commit hooks
          pip install "black==25.9.0" "ruff==0.14.1"

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Run tests (pytest)
        run: pytest -q --tb=short
