name: Codacy Local Analysis (disabled)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Codacy pylint workflow is disabled; Ruff is used for linting."
