name: Codacy Analysis (SARIF)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  codacy-analysis:
    name: Run Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare report folder
        run: mkdir -p codacy_report

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          directory: .
          format: sarif
          output: codacy_report/results.sarif
          gh-code-scanning-compat: true
          # project-token は任意。未設定でもローカルルールで動作可能
          # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codacy_report/results.sarif
